name: mlops
toolchainRegion: 
  valueFrom:
    envVariable: AWS_REGION
forceDependencyRedeploy: true
groups:
  - name: networking
    path: manifests/networking-modules.yaml
  - name: storage
    path: manifests/storage-modules.yaml
  - name: sagemaker-studio
    path: manifests/sagemaker-studio-modules.yaml
  - name: images
    path: manifests/images-modules.yaml
  - name: mlflow
    path: manifests/mlflow-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId:
      valueFrom:
        envVariable: PRIMARY_ACCOUNT
    default: true
    regionMappings:
      - region: 
          valueFrom:
            envVariable: AWS_REGION
        default: true
